### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Xant1k** [firsttris/chrome.removereload#1]
Hello. Thanks you for this.

Can you added Server-bound certificates and Service Workers items for clear too?

Also, i think better add margin-bottom https://vgy.me/hXHrSQ.png for button.

**Comment by firsttris** [comment]
Hey Xant1k,

thx for you feedback.

i found out that i have not implemented "serverBoundCertificates": true
i will add margin to the button too :+1: 

do you know how to deal with Server Worker Items? should we simpy delete them?
http://stackoverflow.com/questions/17490940/how-to-delete-worker-object-in-javascript

regards
Tristan

**Comment by Xant1k** [comment]
> do you know how to deal with Server Worker Items? should we simpy delete them?
try to it:
http://stackoverflow.com/questions/33704791/how-do-i-uninstall-a-service-worker

**Comment by firsttris** [comment]
seems that its not that easily possible to delete serviceWorkers programmically from within a chrome extension.
check for yourself:

- open google.com
- open chrome-dev tools interactive console
- insert code
`navigator.serviceWorker.getRegistrations().then(function(registrations) { console.log(registrations) });`
- you should see a array [ServiceWorkerRegistration]
- open remove&reload options
- open chrome-dev tools interactive console
- insert code
`navigator.serviceWorker.getRegistrations().then(function(registrations) { console.log(registrations) });`
- you should see a empty array

seems that you can only remove them for your current webApp.

I have currently no clue how to do this for each tab

**Comment by firsttris** [comment]
added 
- serverBoundCertificates
- margin-bottom

released a new version 0.0.4

still looking for a way to unregister all serviceWorkers...

**Comment by Xant1k** [comment]
> still looking for a way to unregister all serviceWorkers...
Found this in another extension 
```
{
        "serviceWorkers" : true
      },
```
https://github.com/PrototypeInteractive/chrome-ext-clear-serviceworker/blob/master/popup.js

Ha, google miss it?
https://developer.chrome.com/extensions/browsingData#type-RemovalOptions

And thanks for update, it's work perfectly!

**Comment by firsttris** [comment]
ok, its much more easy than we thought... we just have to add the boolean to browsingData.remove()....

i will update it later..
regards

**Comment by firsttris** [comment]
add remove option for serviceWorkers in 0.0.5.

please check if everything is working as expected.
